WHITE_COLOR = "WHITE"
BLACK_COLOR = "BLACK"

ATTACKING_POSITION = "ATTACKING"
DEFENDING_POSITION = "DEFENDING"
AVAILABLE_POSITION = "AVAILABLE"

NORTH_TO_SOUTH_ORIENTATION = "N -> S"
SOUTH_TO_NORTH_ORIENTATION = "S -> N"

BISHOP_SIGNATURE = "Bi"
KING_SIGNATURE = "Ki"
KNIGHT_SIGNATURE = "Kn"
PAWN_SIGNATURE = "Pa"
QUEEN_SIGNATURE = "Qu"
ROOK_SIGNATURE = "Ro"


